coverage:
    range: 95..100
    round: nearest
    precision: 2

ignore:
    - "src/Dto/*.php"
    - "src/Kernel.php"
    - "src/EvaluatorBundle.php"
    - "bin"
    - "tests"
    - "**/*.md"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.json"
    - "**/*.xml"
    - "**/*.lock"
